### ISSUE TITLE
[Suggestion] Resume/Pause Pregenning

### ISSUE THREAD

**Issue by Towsty** [MattDahEpic/MDECore1.8#11]
At the moment, if the server crashes or is stopped during pregen it seems you must start all over again.

Is it possible to add a way to resume the pregen after a server reboot? Along the same lines to add a /pregen pause command?

**Comment by MattDahEpic** [comment]
I have added pausing, resuming, and cancellation of pregenerations in 1.10.2-1.5.1 and 1.11-1.0. 
I will not be adding persistence of pending generations across server restarts because I have tested the feature and servers that cannot handle pregeneration enter a reboot cycle if the pregeneration is resumed on restart.

**Comment by Towsty** [comment]
Hey, I know this kind of old now - the persistance across reboots wasn't so that someone could have it crash out because of the pregen and keep going. It was so that you could say - pregen 2000x2000 chunks and have it auto restart every hour to avoid it crashing out and have it resume part way through on the reboot. The WorldBorder plugin I think was the one that had this setup, it worked well IF people followed the instructions. 

Thoughts?

**Comment by MattDahEpic** [comment]
The main problem with this is that a large amount of users will attempt to generate an extremely large area on an extremely under powered server and become frustrated when their hardware can't handle it and killing and restarting the server appears to not stop the generation. 
Users don't expect persistence on this and most servers that are able to handle 10 players without lag will be able to generate an area large enough for 10 players (16000x16000 blocks) without needing to restart, providing that it's done with no players on. The only place where this may be a problem is in heavily modded instances, in which clients and servers have to be more beefy anyways.
Either way, pregenerating over an already existing area uses no memory or resources. So generating 1000x1000 *then* 2000x2000 would allow for a restart inbetween and uses no memory when working on the middle 1000x1000 section.
