### ISSUE TITLE
MDECore spamming my console with errors.

### ISSUE THREAD

**Issue by Corcustos** [MattDahEpic/MDECore1.8#12]
I'm getting the following error spammed into my console while I pregen my world.

java.util.ConcurrentModificationExceptionat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211) ~[?:1.8.0_112]at java.util.TreeMap$KeyIterator.next(TreeMap.java:1265) ~[?:1.8.0_112]at net.minecraft.world.WorldServer.func_175712_a(WorldServer.java:664) ~[le.class:?]at net.minecraft.world.WorldServer.func_72920_a(WorldServer.java:642) ~[le.class:?]at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:380) ~[anj.class:?]at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:165) [anj.class:?]at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:238) [ld.class:?]at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:298) [ld.class:?]at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:905) [le.class:?]at com.forgeessentials.backup.ModuleBackup.saveWorld(ModuleBackup.java:392) [ModuleBackup.class:?]at com.forgeessentials.backup.ModuleBackup.backup(ModuleBackup.java:303) [ModuleBackup.class:?]at com.forgeessentials.backup.ModuleBackup.access$000(ModuleBackup.java:60) [ModuleBackup.class:?]at com.forgeessentials.backup.ModuleBackup$4.run(ModuleBackup.java:244) [ModuleBackup$4.class:?]at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

Notable Mods:
Forge: forge-1.8.9-11.15.1.1902-1.8.9-universal.jar
MDECore: mdecore-1.8.9-1.1.4.jar
Pixelmon: Pixelmon-1.8.9-4.3.0-beta10-universal.jar
BiomeTweaker: BiomeTweaker-1.8.9-2.1.211.jar
RTG: RTG-1.8.9-1.0.0-snapshot-3.jar

It would appear that the chunks are still loading, as the regions folder is filling up with chunk data, but it's spamming this error more than once a second. All of my mods are clean installs, as I just installed everything today and started pregenerating my map. All help would be appreciated.

**Comment by MattDahEpic** [comment]
If you could still see if this bug occurs with version 1.10.2-1.3 that would be great.

**Comment by Corcustos** [comment]
I don't plan on using 1.10. I'm just trying to pregenerate my 1.8.9 world so spongeforge doesn't ruin RTG generation as there's a bug in that. If you absolutely really need me to quite literally completely redo my entire server to see if the same bug occurs in a version that I won't ever touch, I can do that. If checking the 1.10.2 version will help the 1.8.9 version, I can do that. Is this the only option right now? (Unless you're telling me to run the 1.10.2 version while everything remains 1.8.9, in which case I can get right on that)

Also, would /mde pregen 1315 1315 0 0 generate 1315 blocks in every direction, or 1315 chunks in every direction? Or neither? I would assume chunks. I'm trying to generate a 42080x42080 world and didn't understand how it worked precisely due to there not being any clarification on this command anywhere that I could find.

**Comment by MattDahEpic** [comment]
I do believe this may not be an issue with MDE Core itself, but pregenerating the amount of chunks you are may be causing a bug in forge essentials' saving code to show itself. The reason I am speculating this is that the stack trace only shows forgeessentials code and that it the error doesn't show up in an instance with only MDE Core and BoP. I would report this bug to forgeessentials as well and refer them back to this issue so they can look to see whether or not my code is at any fault.

As for your question on how the command works, you would be generating every non generated chunk between the chunk coordinates (1315,1315) and (0,0) (about 1.7 million chunks) by using the command you gave.
In order to get the size you want, you would want to use /mde pregen 1315 1315 -1315 -1315

**Comment by Corcustos** [comment]
Thanks! I'm going to try to remove forgeessentials, because I really won't be needing it due to the fact that I'm turning it into a sponge server with PEX for permissions and other individual plugins. Would this help..? Also, the command you specified is for 2630x chunk world, and not 42080 chunks, right? I forgot to specify that 42080 was blocks and not chunks.

**Comment by MattDahEpic** [comment]
Removing forgeessentials should help the console spam. If the bug still occurs without forgeessentials reopen and let me know. And yes, the command I specified was for a 3620x2630 chunk world (42080 blocks by 42080 blocks centered on 0,0).
