### ISSUE TITLE
Pregeneration seems to not decorate the edge chunks when using RTG

### ISSUE THREAD

**Issue by Robijnvogel** [MattDahEpic/MDECore1.8#13]
I've used MDECore, Roguelike Dungeons and RTG to pre-generate a world, which I then uploaded to my Realms (as you know, completely Vanilla). After this, I found that at the edge of the pre-generated chunks, some whole rows of the pre-generated chunks were missing decoration, or had decoration that differed a lot from the neighbouring row of chunks. In some cases, this was the outermost row of chunks and in others this was the row just one further inside.

You can test/reproduce this by using MDECore and RTG to pre-generate a world on a Forge server (client absolutely not needed) and then opening that world in a completely Vanilla launcher. I would recommend pre-generating some small areas with random seeds. Snow is one of the clearest lacking types of decoration.

I don't know for sure if this is MDECore's doing, of course, but I'm letting you know either way.

If you're on the RTG Discord. I've posted some screenshots there in the #offtopic channel.
I know I am a niche case and that that is probably the only reason why I noticed this.

**Comment by MattDahEpic** [comment]
Resolved in 1.10.2-1.5.1 and 1.11-1.0.

**Comment by Robijnvogel** [comment]
I'll test this. :) Thank you!

**Comment by Robijnvogel** [comment]
Looking at the log, it seems to only pregen the (even-x, even-z) chunks.
Or maybe you just changed that to diminish the log-load by 75%?

Anyways, there still is somewhat of a glitch.
I told it to pregen in a radius of 32 chunks, however it seems like the chunks on radius 33 got generated as well.
The outermost half of these (33-radius) chunks seem to be decorated.
The innermost half of these seem not, which in snowy biomes (most visible) results in a snow-less strip of landscape. 

I think this will only be visible if I load an world with using a different generator type than the one it was generated in, though, so I would always set a world-border at the edge of the 32-radius chunks anyway.

EDIT:
This does not seem to happen when using the mod "as intended" so I am very content with how things are right now. Keep up the good work!

**Comment by MattDahEpic** [comment]
For a technical perspective, the way MC decorates chunks is that you have to have the chunk, and the 3 surrounding it on the x and z sides and then MC will decorate it automatically. so the 33rd chunk on that side is generated to facilitate that.
