### ISSUE TITLE
MDECore disabled?

### ISSUE THREAD

**Issue by ghost** [MattDahEpic/MDECore1.8#20]
[11:48:33] [Client thread/WARN] [mdecore-core/]: Mod mdecore-core has been disabled through configuration
Any idea what's disabling MDECore?

**Comment by MattDahEpic** [comment]
MDECore itself is not disabled, that is only the core mod that modifies the tick code for the tickrate command. Everything that coremod does is done by the time the game is loaded, so it gets disabled.

**Comment by ghost** [comment]
That is very cool. Thank you for not leaving loose ends.
