### ISSUE TITLE
[1.10.2-1.5.1] not able to pregen dimension 

### ISSUE THREAD

**Issue by ghost** [MattDahEpic/MDECore1.8#21]
using `command: mde pregen world 0 0 150000 150000` I get `Server thread/INFO Usage: /mde pregen help` both while issueing command on server and on console.

**Comment by MattDahEpic** [comment]
Only numeric dimensions are supported for the dimension argument.

**Comment by MattDahEpic** [comment]
And you have to do mde pregen *start* ...
