### ISSUE TITLE
Feature Suggestion: Kill drops while pregenerating

### ISSUE THREAD

**Issue by MagusLucius** [MattDahEpic/MDECore1.8#23]
when my server is pregenerating chunks, lots of items will be left laying around in unloaded chunks, sometimes tens of thousands of items like BoP Kelp and Coral, Torches and other things, and it really slows down the server even after pregeneration, so I have to go around running /kill @e[type=Item] every few chunks.

It would be nice if MDECore could do this sort of cleanup automatically.

**Comment by MattDahEpic** [comment]
Something has gone wrong if that many items are being left on the ground, normal exploration of the world doesn't usually kill the great coral reef.

Could you see if there's still items being dropped if you pregenerated a world with only MDECore installed? That will help determine if it's a pregeneration issue or a mod interaction issue.

**Comment by MagusLucius** [comment]
I think the problem is the way the coral and kelp are generated. They are disabled by default in the configs, but I like the way they look.

I'm generating chunks now and killing stuff as it goes along.  It's mostly kelp, but also a fair bit of coral and other drops from other mods like railcraft rails and crystal essence from TC6, glow-shrooms from botania, torches... a lot of this is possibly stuff displaced by water.

I did get a warning about something trying to "Over-fill a container", but it went by too fast for me to catch more than that.

I don't think it's a problem with your mod, but I thought I'd make a suggestion.

**Comment by MattDahEpic** [comment]
I will take a look at adding a config option for this next time I'm working with MDECore (probably next version update). Thank you for the feedback!
