### ISSUE TITLE
Replay Mod incompatible

### ISSUE THREAD

**Issue by salniukas** [MattDahEpic/MDECore1.8#24]
The MDEcore alone with replay mode, makes Replay mod unusable.
Replay mod --> Preview Replay And menu becomes in-active so it becomes unusable. The only way to close it is to force close minecraft (Like Alt+f4)

**Comment by MattDahEpic** [comment]
If I could get the version of both mods please.

**Comment by salniukas** [comment]
mdecore-1.12-1.0
Replay Mod v1.12.2-2.1.1
