### ISSUE TITLE
MDECore does support 1.16.5

### ISSUE THREAD

**Issue by ModernGamingWorld** [MattDahEpic/MDECore1.8#26]
It seems that Auto Ore Dictionary Converter supports 1.16.5, but your MDECores does not and wont sync with modpacks using 1.16.5

**Comment by MattDahEpic** [comment]
Doh! Thanks for letting me know, it should be updated now!

**Comment by Blackcatmaxy** [comment]
Modrinth is missing the 1.16.5 version, I would really like to use the Auto Ore Dictionary Converter in my Modrinth pack but this repository is also missing a license.

**Comment by MattDahEpic** [comment]
The 1.16.5 version was on Modrinth, just not tagged correctly. That is now fixed. I will add the requisite license to the repository here
