### ISSUE TITLE
Client crash upon joining server (1.8.9)

### ISSUE THREAD

**Issue by kwpugh** [MattDahEpic/MDECore1.8#3]
Using:
- mdecore-1.8.9-1.1.1.jar
- ringkydinks-1.8.9-alpha5.jar

Crash report:  http://pastebin.com/raw/4rBscdzi

**Comment by MattDahEpic** [comment]
Does this bug occur in a new world? In a new world with a new uphill step assist dink?

**Comment by kwpugh** [comment]
This is in an existing world, server-based.   I do not know if any players have built an uphill assist dink.
No Opis sadly.

**Comment by MattDahEpic** [comment]
Try creating a new world. Does the bug still occur? In that new world, does the bug occur with or without a uphill step assist dink?

**Comment by MattDahEpic** [comment]
Ringkydinks has changed how it's items are identified a few times. If the bug occurs on a new world it's a code problem, if not it's a bug that only occurs on items converted from previous formats.

**Comment by kwpugh** [comment]
so if I remove the mods from the server, restart to allow the server to remove the items, and then add the new version, it should be ok?

**Comment by MattDahEpic** [comment]
I would not know if it fixes the issue because you haven't told me if the bug occurs in a new world.

**Comment by kwpugh** [comment]
Checking on that now, I needed to setup a new server to test it.

**Comment by kwpugh** [comment]
So, I setup another server with a fresh world folder using:
- mdecore 1.1.1
- ringkydink alpha5

server starts up fine, but still get client crash trying to join.

crash report:  http://pastebin.com/raw/3JkFtbfB

**Comment by MattDahEpic** [comment]
I have identified the bug and have fixed it in a developer environment. As I am in the middle of finishing the code for the rubber hand and chest dink I cannot create a new release at the moment. This week is finals week so expect a new release the week after next.

**Comment by kwpugh** [comment]
Thank you and good luck on your finals!!!

**Comment by MattDahEpic** [comment]
alpha6 is available for download!

**Comment by kwpugh** [comment]
Thank you.   Hope finals went well.
