### ISSUE TITLE
 mdecore crashes dedicated forge server 1.9 on startup while looking client side classes

### ISSUE THREAD

**Issue by kreezxil** [MattDahEpic/MDECore1.8#4]
Issue: mdecore{1.9-0.1} crashes dedicated forge server 1.9 build 1804 on startup while looking entityplayersp classes

crash report:
https://gist.github.com/8c1f69d24006f30e18c3

fml server latest:
https://gist.github.com/495eeffa31f17ee0d09c

**Comment by MattDahEpic** [comment]
Fixed in 1.9-0.2.

**Comment by kreezxil** [comment]
Grrr, shame on me for getting the latest builds on forge.

Issue: mdecore{1.9-0.2} crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/21de46500808b7a09171

fml server latest:
https://gist.github.com/bc53a82e9e8a8c5840c3

**Comment by MattDahEpic** [comment]
Try 1.9-0.3?

**Comment by MattDahEpic** [comment]
Also try 1.9-0.4, there's some rendering changes in there.

**Comment by MattDahEpic** [comment]
Assuming fixed, if issue still exists in 1.9-0.5, please reopen.
