### ISSUE TITLE
Use of MDECore.logger in transformer results in certain classes being class loaded too early

### ISSUE THREAD

**Issue by gabizou** [MattDahEpic/MDECore1.8#5]
From the issue on [SpongeForge](https://github.com/SpongePowered/SpongeForge/issues/585#issuecomment-203030464), we are a core-mod as well where we transform various classes to implement our API, and namely one of them being the `net.minecraft.item.Item` class. Unfortunately, because your transformer is invoking `MDECore.logger` [here](https://github.com/MattDahEpic/MDECore/blob/1.9.X/src/main/java/com/mattdahepic/mdecore/asm/TickrateTransformer.java#L19), the class `MDECore` is being class loaded and thusly class initialized, which results in your [DebugItem](https://github.com/MattDahEpic/MDECore/blob/1.9.X/src/main/java/com/mattdahepic/mdecore/MDECore.java#L47) being class loaded as well. 

The root of the problem with all of this is that by class loading some of these classes so early results in the inability for other core-mods being able to transform those classes (and `Item` is one such class that a few core-mods do require transforming to work).

A simple fix could be either using `System.out.println`, or moving your logger to it's own util class _that doesn't class load anything else during static initialization_. 

Hell, a different solution would be to use lazy initialization via delegated method.

**Comment by MattDahEpic** [comment]
Fixed in 1.9-0.4.

**Comment by gabizou** [comment]
@MattDahEpic And any chance on a back port fix for 1.8.9 versions?

**Comment by MattDahEpic** [comment]
@gabizou [Yup.](http://minecraft.curseforge.com/projects/mattdahepic-core/files/2291993)

**Comment by gabizou** [comment]
Many thanks @MattDahEpic :)
